/**
 * DEPRECATED — do not write public/sitemap.xml.
 *
 * Next.js serves the complete sitemap from `app/sitemap.ts` at /sitemap.xml.
 * A file in public/ would override that metadata route and shrink the index
 * back to home + cases.
 *
 * Kept so existing CI scripts (`npm run generate:sitemap`) exit cleanly.
 */
console.log(
  '⚠️  sitemap.mjs is deprecated. Sitemap is generated by app/sitemap.ts (Next.js Metadata Route).',
);
console.log('   Do not write public/sitemap.xml — it would override /sitemap.xml.');
process.exit(0);
